server {
    listen 80;
    server_name localhost;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    # El proxy de /api lo manejaremos en el Caddy Global 
    # para no tener configuraciones duplicadas.
}